### ISSUE TITLE
Remove Special day -icons

### ISSUE THREAD

**Issue by AnttiRumpunen** [smartmet-jm/weather-app#1]
Finnish version have special icons for certain dates like 1st of May. These are unnecessary in Jamaican version.

**Comment by evnurm-cgi** [comment]
I checked the implementation of this and found that these icons are never shown unless the default location is in Finland (`Config.get('location')?.default?.country === 'FI'`). Is this check sufficient or should we remove the icons and related logic from the application? Leaving the code unchanged would make maintenance easier (no conflicts with the main weather-app repository).

**Comment by AnttiRumpunen** [comment]
Current implementation may be enough. Although this should probably be in config instead of hardcoded.
