### ISSUE TITLE
Gust, humidity and day length should be ON by default

### ISSUE THREAD

**Issue by AnttiRumpunen** [smartmet-jm/weather-app#11]
Simple defaultConfig change?

**Comment by AnttiRumpunen** [comment]
Gust and humidity set ON by default

**Comment by AnttiRumpunen** [comment]
Couldn't find settings to set day length on by default...

**Comment by evnurm-cgi** [comment]
Setting this as `weather.forecast.defaultParameters` selects gust and humidity to be shown by default.
```
defaultParameters: [
   // ...
  'hourlymaximumgust',
  'humidity',
],
```

At the moment, there is no way to choose day length to be shown by default - support for this has to be implemented.

**Comment by AnttiRumpunen** [comment]
Smartmet Server's available data: https://data.metservice.gov.jm/admin?what=qengine (app is using meteor -producer)

Example timeseries query which fetches data for defined parameters: https://data.metservice.gov.jm/timeseries?format=debug&producer=meteor&latlon=18.03555,-76.8516513&precision=double&param=name,time,Temperature,%20DewPoint,%20ProbabilityThunderstorm,%20Pressure,%20Humidity,%20WindSpeedMS,%20WindDirection,%20WindVectorMS,%20HourlyMaximumGust,%20WindUMS,%20WindVMS,%20TotalCloudCover,%20LowCloudCover,%20MediumCloudCover,%20HighCloudCover,%20MiddleAndLowCloudCover,%20Precipitation1h,%20PrecipitationForm,%20PrecipitationType,%20ProbabilityThunderstorm,%20FogIntensity,%20WeatherSymbol3,%20WeatherSymbol1,%20PoP,%20HourlyMaximumWindSpeed,%20GeopHeight

As we can see hourlymaximumgust returns empty values.

**Comment by AnttiRumpunen** [comment]
The problem is that hourlymaximumgust is not being edited by Jamaicans. Once it's edited into the data, it will work

**Comment by AnttiRumpunen** [comment]
settings added to defaultSettings.ts
