### ISSUE TITLE
Incorrect colors in rainfall WMS-layer

### ISSUE THREAD

**Issue by AnttiRumpunen** [smartmet-jm/weather-app#9]
Should be same as in info-panel.

I believe this requires new styles to WMS-layer.

Color values:
export const RAIN_1_LIGHT = 'rgb(208,219,239)';
export const RAIN_3_LIGHT = 'rgb(134,152,211)';
export const RAIN_5_LIGHT = 'rgb(11,89,178)';
export const RAIN_8_LIGHT = 'rgb(91,26,142)';

**Comment by AnttiRumpunen** [comment]
ASP is responsible of this change since it requires modifying Smartmet Server's WMS-layer configs.

**Comment by mrauhala** [comment]
Needed colors are mentioned, what are the thresholds for colors?
